version: '3'

services:
  library.notificationservice:
    build: ./Library.NotificationService2
    image: microservices:clients
    restart: on-failure
    networks:
      - api
    ports:
      - "82:80"
    depends_on:
      - library.webapi
      - rabbit
        
  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    networks:
      - api

networks:
  api:
    driver: bridge