version: '3'

services:
 
  library.notificationservice:
    build: ./Library.NotificationService2
    image: library:notificationservice
    restart: on-failure
    environment:
      - RABBITMQ__SERVERADDRESS=rabbitmq://rabbit
      - RABBITMQ__PASSWORD=admin
      - RABBITMQ__USERNAME=admin
    networks:
      - api
    ports:
      - "92:80"
    depends_on:
      - rabbit
        
  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    networks:
      - api

networks:
  api:
    driver: bridge