version: '3'

services:

  library.web:
    build: ./Library.Web
    image: library:web
    networks:
      - api
    ports:
      - "90:80"
    environment:
      - LibraryWebApiServiceHost=http://library.webapi
    depends_on:
      - library.webapi

  library.webapi:
    build: ./Library.WebApi
    image: library:webapi
    restart: on-failure
    environment:
      - RABBITMQ__SERVERADDRESS=rabbitmq://rabbit
      - RABBITMQ__PASSWORD=admin
      - RABBITMQ__USERNAME=admin
    networks:
      - api
    ports:
      - "91:80"
    depends_on:
      - rabbit
    links:
      - rabbit
 
  library.notificationservice:
    build: ./Library.NotificationService2
    image: microservices:clients
    restart: on-failure
    environment:
      - RABBITMQ__SERVERADDRESS=rabbitmq://rabbit
      - RABBITMQ__PASSWORD=admin
      - RABBITMQ__USERNAME=admin
    networks:
      - api
    ports:
      - "92:80"
    depends_on:
      - library.webapi
      - rabbit
        
  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    networks:
      - api

networks:
  api:
    driver: bridge